#!/usr/bin/env bash
# Sets traps for SIGTERM, SIGINT, and SIGQUIT.
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"
function sigterm {
    echo "I hate the kill command"
    sudo rm -f /var/run/holbertonscript.pid
    exit
}

function sigint {
    echo "Y U no love me?!"
    exit
}

function sigquit {
    sudo rm -f /var/run/holbertonscript.pid
    exit
}

trap sigterm SIGTERM
trap sigint SIGINT
trap sigquit SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
