#!/usr/bin/env bash
# Prints bad luck and good luck on the 4th and 8th iterations.
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	(( i++ ))
done
exit 0
